// createTableString; A string that represents the create statement, which hive 
// will execute to generate the table (wiki_events) this program analyzes.

package project1

object createTableString {
    val fields = """
        wiki_db String,
        event_entity String,
        event_type String,
        event_timestamp String,
        event_comment_escaped String,

        event_user_id Int,
        event_user_text_historical_escaped String,
        event_user_text_escaped String,
        event_user_blocks_historical_string String,
        event_user_blocks_string String,
        event_user_groups_historical_string String,
        event_user_groups_string String,
        event_user_is_bot_by_historical_string String,
        event_user_is_bot_by_string String,
        event_user_is_created_by_self Boolean,
        event_user_is_created_by_system Boolean,
        event_user_is_created_by_peer Boolean,
        event_user_is_anonymous Boolean,
        event_user_registration_timestamp String,
        event_user_creation_timestamp String,
        event_user_first_edit_timestamp String,
        event_user_revision_count  Int,
        event_user_seconds_since_previous_revision  Int,

        page_id  Int,
        page_title_historical String,
        page_title String,
        page_namespace_historical Integer,
        page_namespace_is_content_historical Boolean,
        page_namespace Integer,
        page_namespace_is_content Boolean,
        page_is_redirect Boolean,
        page_is_deleted Boolean,
        page_creation_timestamp String,
        page_first_edit_timestamp String,
        page_revision_count  Int,
        page_seconds_since_previous_revision  Int,

        user_id  Int,
        user_text_historical_escaped  String,
        user_text_escaped String,
        user_blocks_historical_string String,
        user_blocks_string String,
        user_groups_historical_string String,
        user_groups_string String,
        user_is_bot_by_historical_string String,
        user_is_bot_by_string String,
        user_is_created_by_self Boolean,
        user_is_created_by_system Boolean,
        user_is_created_by_peer Boolean,
        user_is_anonymous Boolean,
        user_registration_timestamp String,
        user_creation_timestamp String,
        user_first_edit_timestamp String,

        revision_id  Int,
        revision_parent_id  Int,
        revision_minor_edit Boolean,
        revision_deleted_parts_string String,
        revision_deleted_parts_are_suppressed Boolean,
        revision_text_bytes  Int,
        revision_text_bytes_diff  Int,
        revision_text_sha1 String,
        revision_content_model String,
        revision_content_format String,
        revision_is_deleted_by_page_deletion Boolean,
        revision_deleted_by_page_deletion_timestamp String,
        revision_is_identity_reverted Boolean,
        revision_first_identity_reverting_revision_id  Int,
        revision_seconds_to_identity_revert  Int,
        revision_is_identity_revert Boolean,
        revision_is_from_before_page_creation Boolean,
        revision_tags_string String   
    """

    val s = f"create table if not exists wiki_events($fields) row format delimited fields terminated by '\t'"
}
